# Generated by Django 4.0.6 on 2022-08-21 21:50

from django.db import migrations, models
import dnaquery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNA_Protein_Alignment_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_seq', dnaquery.models.DNAQuerySeqField(max_length=30000, validators=[dnaquery.models.validate_dna])),
                ('alignment_status', models.CharField(default='RECIEVED', max_length=3000)),
                ('results', models.CharField(blank=True, default='(no results yet)', max_length=300)),
            ],
        ),
    ]
